### Get user(id = admin)
GET http://localhost:8080/users/admin

### Get user(id = nhn)
GET http://localhost:8080/users/nhn

### Create user(id = nhn)
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "nhn",
  "password": "academy"
}

### Get user(id = nhn)
GET http://localhost:8080/users/nhn

### Modify user(id = nhn)
PUT http://localhost:8080/users/nhn
Content-Type: application/json

{
  "password": "hahaha"
}

### Create user(id = user)
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "user",
  "password": "1234",
  "age" : 26
}

### Get user(id = user)
GET http://localhost:8080/users/user

### Modify user(id = user)
PUT http://localhost:8080/users/user
Content-Type: application/json

{
  "password": "hahaha",
  "age" : 29
}


